
--1. Crear una base de datos de nombre Jurassic_Park sin especificar los valores de la base. 

CREATE DATABASE Jurassic_Park;

--2. Crear la tabla Escuela y definir su clave principal en la misma instrucción de creación. 
--   Continuar con tablas Guia, Reserva y Tipo_Visita. 

	USE Jurassic_Park;
	 
	CREATE TABLE JPESCESCM(
		ESCESC_CODIGO INT PRIMARY KEY,
		ESCESC_NOMBRE VARCHAR(50) NOT NULL, 
		ESCESC_DOMICILIO VARCHAR(100) NOT NULL
	);
	
	CREATE TABLE JPRESGUIM(
		RESGUI_CODIGO INT PRIMARY KEY,
		RESGUI_NOMBRES VARCHAR(20) NOT NULL, 
		RESGUI_APELLIDOS VARCHAR(20) NOT NULL
	);
	
	CREATE TABLE JPRESRESM(
		RESRES_NUMERO INT PRIMARY KEY,
		RESRES_FECHA_VIS_RES DATE NOT NULL, 
		RESRES_HORA_VIS_RES TIME NOT NULL, 
		ESCESC_CODIGO INT
	);

	CREATE TABLE JPRESTVIM(
		RESTVI_CODIGO INT PRIMARY KEY,
		RESTVI_DESCRIPCION VARCHAR(30) NOT NULL, 
		RESTVI_ARANCEL_POR_ALUMNO FLOAT NOT NULL
	);
	

--3. Crear la tabla Telefono_Escuela con su clave principal. (hacer restricción en caso de ser una CP compuesta). 

	CREATE TABLE JPESCTESD(
		ESCESC_CODIGO INT NOT NULL,
		ESCTES_TELEFONO BIGINT NOT NULL
	);
	
	ALTER TABLE JPESCTESD 
	ADD CONSTRAINT JPESCTESD_PK PRIMARY KEY (ESCESC_CODIGO, ESCTES_TELEFONO);

--4. Crear la tabla Reserva_Por_Grado con su clave principal. Hacer las correspondientes restricciones. 

	CREATE TABLE JPRESRGRD(
		RESRES_NUMERO INT NOT NULL,
		RESTVI_CODIGO INT NOT NULL,
		RESRGR_GRADO VARCHAR(10) NOT NULL
	);
	
	ALTER TABLE JPRESRGRD 
	ADD CONSTRAINT PRESRGRD_PK PRIMARY KEY (RESRES_NUMERO, RESTVI_CODIGO, RESRGR_GRADO);

--5. Crear la tabla Reserva_Tipo_Visita con sus campos propios y los referenciados. Sin generar claves. 
	
	CREATE TABLE JPRESRTVD(
		RESRES_NUMERO INT NOT NULL,
		RESTVI_CODIGO INT NOT NULL,
		RESRTV_CANT_ALUM_RES INT NOT NULL, 
		RESRTV_CANT_ALUM_REAL INT NOT NULL,
		RESGUI_CODIGO INT NOT NULL
	);

--6. Completar el ejercicio anterior, con la creación de las claves correspondientes. 

	--Clave foránea de tabla JPESCTESD
	ALTER TABLE JPESCTESD
	ADD CONSTRAINT JPESCTESD_ESCESC_CODIGO_FK 
		FOREIGN KEY (ESCESC_CODIGO) REFERENCES JPESCESCM (ESCESC_CODIGO);
	
	
	--Clave foránea de tabla JPRESRESM
	ALTER TABLE JPRESRESM
	ADD CONSTRAINT JPRESRESM_ESCESC_CODIGO_FK
		FOREIGN KEY (ESCESC_CODIGO) REFERENCES JPESCESCM (ESCESC_CODIGO);
	
	--Claves foráneas de tabla JPRESRTVD
	ALTER TABLE JPRESRTVD
	ADD CONSTRAINT JPRESRTVD_RESRES_NUMERO_FK
		FOREIGN KEY (RESRES_NUMERO) REFERENCES JPRESRESM (RESRES_NUMERO);
		
	ALTER TABLE JPRESRTVD
	ADD CONSTRAINT JPRESRTVD_RESTVI_CODIGO_FK
		FOREIGN KEY (RESTVI_CODIGO) REFERENCES JPRESTVIM (RESTVI_CODIGO);
		
	--Claves foráneas de tabla JPRESRGRD
	ALTER TABLE JPRESRGRD
	ADD CONSTRAINT JPRESRGRD_RESRES_NUMERO_FK
		FOREIGN KEY (RESRES_NUMERO) REFERENCES JPRESRESM (RESRES_NUMERO);
		
	ALTER TABLE JPRESRGRD
	ADD CONSTRAINT JPRESRGRD_RESTVI_CODIGO_FK
		FOREIGN KEY (RESTVI_CODIGO) REFERENCES JPRESTVIM (RESTVI_CODIGO);	
	
		
--7. Añadir a la tabla de Guía la columna sueldo_hora. 
--Nota: En SQL Server no es necesario agregar COLUMN. 

	ALTER TABLE JPRESGUIM
	ADD RESGUI_SUELDO_HORA FLOAT NOT NULL;
	
--8. Hacer que no puedan haber dos escuelas con el mismo nombre. 

	ALTER TABLE JPESCESCM
	ADD CONSTRAINT ESCESC_NOMBRE_UNIQUE UNIQUE (ESCESC_NOMBRE);

--CLASE 1 - Adicionales 

--1. Crear la tabla Distrito_Escolar con su correspondiente CP. 

	CREATE TABLE JPESCDESM(
		ESCDES_CODIGO INT PRIMARY KEY,
		ESCDES_DESCRIPCION VARCHAR(20) NOT NULL
	);
	
--2. Agregar clave foránea codigo_distrito_escolar a la tabla Escuela 

	ALTER TABLE JPESCESCM
	ADD ESCDES_CODIGO INT NOT NULL;
	
	ALTER TABLE JPESCESCM
	ADD CONSTRAINT JPESCESCM_ESCDES_CODIGO_FK
		FOREIGN KEY (ESCDES_CODIGO) REFERENCES JPESCDESM (ESCDES_CODIGO);

--3. Eliminar la columna de domicilios de la tabla Escuela. 

	ALTER TABLE JPESCESCM
	DROP COLUMN ESCESC_DOMICILIO;

--4. Agregar columnas calle_escuela y altura_escuela a la tabla Escuela. 

	ALTER TABLE JPESCESCM
	ADD ESCESC_CALLE VARCHAR(50), ESCESC_ALTURA FLOAT;

--5. Agregar domicilio_guia en tabla Guia. 
	
	ALTER TABLE JPRESGUIM
	ADD RESGUI_DOMICILIO VARCHAR(50) NOT NULL;

--6. Eliminar tabla Telefono_Escuela 

	DROP TABLE JPESCTESD;

--7. Agregar tabla Email_Escuela (sin Clave primaria) 
	
	CREATE TABLE JPESCEESD(
		ESCEES_CODIGO INT NOT NULL,
		ESCEES_DESCRIPCION VARCHAR(30) NOT NULL
	);

--8. Establecer clave primaria para Email_Escuela 

	ALTER TABLE JPESCEESD
	ADD CONSTRAINT JPESCEESD_PK PRIMARY KEY (ESCEES_CODIGO);

--9. Establecer que los nombres y apellidos de los guias no tengan valores nulos. nulos. 

	ALTER TABLE JPRESGUIM
	ADD CONSTRAINT JPRESGUIM_NOMBRES_APELLIDOS_CHK
	CHECK ((RESGUI_NOMBRES IS NOT NULL) AND (RESGUI_APELLIDOS IS NOT NULL));

--10. Establecer que no se repita la calle y la altura de las escuelas. 
	
	ALTER TABLE JPESCESCM
	ADD CONSTRAINT JPESCESCM_CALLE_ALTURA_UK
		UNIQUE (ESCESC_CALLE, ESCESC_ALTURA);
